"""ORM models for Grid entities — CMZs, GridNodes, and GridAlerts."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import Boolean, DateTime, Float, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.core.utils import new_uuid, utcnow


class CMZ(Base):
    """Constraint Managed Zone — a geographic/electrical zone with import/export limits."""

    __tablename__ = "cmzs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    deployment_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    slug: Mapped[str] = mapped_column(String(128), nullable=False, index=True)  # e.g. "CMZ-SHETLAND"
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    topology_type: Mapped[str] = mapped_column(String(32), nullable=False)  # ISLAND / RADIAL / MESHED
    max_import_kw: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    max_export_kw: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    voltage_nominal_v: Mapped[float] = mapped_column(Float, nullable=False, default=230.0)
    feeder_ids: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON array of feeder node IDs
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow)

    def __repr__(self) -> str:
        return f"<CMZ slug={self.slug} deployment={self.deployment_id}>"


class GridNode(Base):
    """
    Distribution grid node — a feeder, distribution transformer, or substation.
    Carries real-time telemetry (loading %, voltage) updated by the simulation loop.
    """

    __tablename__ = "grid_nodes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    deployment_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    node_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)  # e.g. "FDR-01"
    cmz_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)  # slug of parent CMZ
    node_type: Mapped[str] = mapped_column(String(32), nullable=False)  # FEEDER / DISTRIBUTION_TRANSFORMER / SUBSTATION
    name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Electrical ratings
    voltage_kv: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rated_mva: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rated_kva: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Real-time telemetry (updated every simulation tick)
    current_loading_pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    voltage_l1_v: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    voltage_l2_v: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    voltage_l3_v: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Hosting capacity
    hosting_capacity_kw: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    used_capacity_kw: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Geography
    lat: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    lng: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # CIM integration reference
    cim_id: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow)

    def __repr__(self) -> str:
        return f"<GridNode node_id={self.node_id} type={self.node_type} deploy={self.deployment_id}>"


class GridAlert(Base):
    """
    Real-time grid alert generated by the simulation/dispatch engine.
    Can be acknowledged by operators and resolved when the condition clears.
    """

    __tablename__ = "grid_alerts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    deployment_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    node_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True, index=True)
    asset_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)

    # OVERVOLTAGE / UNDERVOLTAGE / OVERLOAD / HOSTING_CAPACITY / OFFLINE_ASSET / DR_UNDERDELIVERY
    alert_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)  # CRITICAL / WARNING / INFO

    message: Mapped[str] = mapped_column(Text, nullable=False)

    is_acknowledged: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    acknowledged_by: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    meta: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON

    def __repr__(self) -> str:
        return f"<GridAlert type={self.alert_type} severity={self.severity} node={self.node_id}>"
